# Generated by Django 3.2.3 on 2021-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('link_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(null=True)),
                ('posted_by', models.CharField(max_length=300)),
                ('content', models.TextField(unique=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('date_posted', models.DateTimeField(null=True)),
                ('favourite_count', models.IntegerField(default=0)),
                ('retweet_count', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('links', models.ManyToManyField(to='tweets.Link')),
            ],
        ),
    ]
