# Generated by Django 3.2.3 on 2021-05-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
